/*
 * generated by Xtext
 */
package org.eclipse.xtext.graphview.map.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.xtext.graphview.map.ui.internal.GraphViewMappingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GraphViewMappingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GraphViewMappingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GraphViewMappingActivator.getInstance().getInjector(GraphViewMappingActivator.ORG_ECLIPSE_XTEXT_GRAPHVIEW_MAP_GRAPHVIEWMAPPING);
	}
	
}
