<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graphViewMapping" nsURI="http://www.eclipse.org/xtext/graphview/map/GraphViewMapping"
    nsPrefix="graphViewMapping">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMapping" abstract="true" eSuperTypes="../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmIdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unlessCondition" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hidden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMappingDefinition" eSuperTypes="#//AbstractMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//AbstractExpressionMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractExpressionMapping" eSuperTypes="#//AbstractMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMappingReference" eSuperTypes="#//AbstractExpressionMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedMapping" eType="#//AbstractMappingDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="call" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramMapping" eSuperTypes="#//AbstractMappingDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importSection" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xtype.ecore#//XImportSection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeGuard" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeMapping" eSuperTypes="#//AbstractMappingDefinition #//AbstractExpressionMapping"/>
  <eClassifiers xsi:type="ecore:EClass" name="LabelMapping" eSuperTypes="#//AbstractMappingDefinition #//AbstractExpressionMapping"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeMapping" eSuperTypes="#//AbstractMappingDefinition #//AbstractExpressionMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceMapping" eType="#//EdgeEndMapping"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetMapping" eType="#//EdgeEndMapping"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeEndMapping" eSuperTypes="#//AbstractMappingReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingCall" eSuperTypes="#//AbstractMappingReference"/>
</ecore:EPackage>
