/*
 * generated by Xtext
 */
package org.eclipse.xtext.graphview.style;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GraphViewStyleRuntimeModule extends org.eclipse.xtext.graphview.style.AbstractGraphViewStyleRuntimeModule {

}
