/*
 * generated by Xtext
 */
package org.eclipse.xtext.graphview.style.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GraphViewStyleUiModule extends org.eclipse.xtext.graphview.style.ui.AbstractGraphViewStyleUiModule {
	public GraphViewStyleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
