/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.xtext.graphview.map.graphViewMapping.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.graphview.map.graphViewMapping.AbstractExpressionMapping;
import org.eclipse.xtext.xbase.XExpression;

/**
 * A sample validator interface for {@link org.eclipse.xtext.graphview.map.graphViewMapping.AbstractExpressionMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractExpressionMappingValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateMulti(boolean value);
	boolean validateExpression(XExpression value);

	boolean validateContents(EList<AbstractExpressionMapping> value);
}
