/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.xtext.graphview.map.graphViewMapping.validation;

import org.eclipse.xtext.xbase.XExpression;
import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.graphview.map.graphViewMapping.AbstractExpressionMapping;

/**
 * A sample validator interface for {@link org.eclipse.xtext.graphview.map.graphViewMapping.AbstractMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractMappingValidator {
	boolean validate();

	boolean validateUnlessCondition(XExpression value);

	boolean validateSkip(boolean value);

	boolean validateMappings(EList<AbstractExpressionMapping> value);
	boolean validateName(String value);
}
