/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.xtext.graphview.map.graphViewMapping.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.common.types.JvmParameterizedTypeReference;
import org.eclipse.xtext.common.types.JvmTypeReference;
import org.eclipse.xtext.graphview.map.graphViewMapping.Import;

/**
 * A sample validator interface for {@link org.eclipse.xtext.graphview.map.graphViewMapping.DiagramMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DiagramMappingValidator {
	boolean validate();

	boolean validateImports(EList<Import> value);
	boolean validateTypeGuard(JvmTypeReference value);

	boolean validateTypeGuard(JvmParameterizedTypeReference value);
}
