/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.xtext.graphview.map.graphViewMapping.validation;

import org.eclipse.xtext.graphview.map.graphViewMapping.AbstractMapping;
import org.eclipse.xtext.graphview.map.graphViewMapping.AbstractExpressionMapping;

/**
 * A sample validator interface for {@link org.eclipse.xtext.graphview.map.graphViewMapping.MappingCall}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MappingCallValidator {
	boolean validate();

	boolean validateMapping(AbstractMapping value);

	boolean validateMapping(AbstractExpressionMapping value);
}
