<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graphViewStyle" nsURI="http://www.xtext.org/graphview/style/GraphViewStyle"
    nsPrefix="graphViewStyle">
  <eClassifiers xsi:type="ecore:EClass" name="StyleSheet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importSection" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xtype.ecore#//XImportSection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramMapping" eType="ecore:EClass ../../org.eclipse.xtext.graphview.map/model/GraphViewMapping.ecore#//DiagramMapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="styles" upperBound="-1"
        eType="#//Style" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Style" eSuperTypes="../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmIdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" unique="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.xtext.graphview.map/model/GraphViewMapping.ecore#//AbstractMapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="javaClass" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XColorLiteral" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
