/*
 * generated by Xtext
 */
package org.eclipse.xtext.graphview.style.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GraphViewStyleAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/xtext/graphview/style/parser/antlr/internal/InternalGraphViewStyle.tokens");
	}
}
