/*
* generated by Xtext
*/
package org.eclipse.xtext.graphview.style.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class GraphViewStyleOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
