/*
 * generated by Xtext
 */
package org.eclipse.xtext.graphview.map;

import org.eclipse.xtext.graphview.map.scoping.GraphViewMappingIdentifiableSimpleNameProvider;
import org.eclipse.xtext.graphview.map.types.GraphViewMappingTypeProvider;
import org.eclipse.xtext.xbase.featurecalls.IdentifiableSimpleNameProvider;
import org.eclipse.xtext.xbase.typing.ITypeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("restriction")
public class GraphViewMappingRuntimeModule extends org.eclipse.xtext.graphview.map.AbstractGraphViewMappingRuntimeModule {

	@Override
	public Class<? extends ITypeProvider> bindITypeProvider() {
		return GraphViewMappingTypeProvider.class;
	}
	
	@Override
	public Class<? extends IdentifiableSimpleNameProvider> bindIdentifiableSimpleNameProvider() {
		return GraphViewMappingIdentifiableSimpleNameProvider.class;
	}
}
