/*
 * generated by Xtext
 */
package org.eclipse.xtext.graphview.map.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.graphview.map.ui.highlighting.GVMHighlightingCalculator;
import org.eclipse.xtext.graphview.map.ui.highlighting.GVMHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GraphViewMappingUiModule extends org.eclipse.xtext.graphview.map.ui.AbstractGraphViewMappingUiModule {
	public GraphViewMappingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return GVMHighlightingCalculator.class;
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return GVMHighlightingConfiguration.class;
	}
}
