/*
 * generated by Xtext
 */
package org.eclipse.xtext.graphview.map.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GraphViewMappingUiModule extends org.eclipse.xtext.graphview.map.ui.AbstractGraphViewMappingUiModule {
	public GraphViewMappingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
