/*
 * generated by Xtext
 */
package org.eclipse.xtext.graphview.style.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.xtext.graphview.style.ui.internal.GraphViewStyleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GraphViewStyleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GraphViewStyleActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GraphViewStyleActivator.getInstance().getInjector(GraphViewStyleActivator.ORG_ECLIPSE_XTEXT_GRAPHVIEW_STYLE_GRAPHVIEWSTYLE);
	}
	
}
