/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.xtext.graphview.instancemodel.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.graphview.instancemodel.AbstractInstance;
import org.eclipse.xtext.graphview.instancemodel.Visibility;
import org.eclipse.xtext.graphview.instancemodel.ViewState;
import org.eclipse.xtext.graphview.map.graphViewMapping.AbstractMapping;

/**
 * A sample validator interface for {@link org.eclipse.xtext.graphview.instancemodel.AbstractInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractInstanceValidator {
	boolean validate();

	boolean validateParent(AbstractInstance value);
	boolean validateChildren(EList<AbstractInstance> value);

	boolean validateSemanticElement(Object value);

	boolean validateMapping(AbstractMapping value);

	boolean validateVisibility(Visibility value);

	boolean validateVisibility(ViewState value);

	boolean validateMapping(EObject value);
}
