/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.xtext.graphview.instancemodel.validation;

import org.eclipse.xtext.graphview.instancemodel.NodeInstance;

/**
 * A sample validator interface for {@link org.eclipse.xtext.graphview.instancemodel.EdgeInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EdgeInstanceValidator {
	boolean validate();

	boolean validateSource(NodeInstance value);
	boolean validateTarget(NodeInstance value);
}
