/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.xtext.graphview.instancemodel.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.graphview.instancemodel.EdgeInstance;


/**
 * A sample validator interface for {@link org.eclipse.xtext.graphview.instancemodel.NodeInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeInstanceValidator {
	boolean validate();

	boolean validateOutgoingEdges(EList<EdgeInstance> value);

	boolean validateIncomingEdges(EList<EdgeInstance> value);

}
